version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@db:3306/database"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./pokerserver
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE: "http://backend:8000"
    volumes:
      - ./pokerserver:/app 
    depends_on:
      - backend

volumes:
  db-data: